diarytracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path("accounts/signup/", views.signup, name='signup'),
    path('diary/', views.diary_index, name='diary-index'),
    path('diary/<int:diary_id>/', views.diary_detail, name='diary-detail'),
    path('diary/<int:diary_id>/add-physical/', views.add_physical, name='add-physical'),
    path('diary/<int:diary_id>/add-mental/', views.add_mental, name='add-mental'),
    path('diary/<int:diary_id>/add-emotional/', views.add_emotional, name='add-emotional'),
    path('diary/mental/<int:pk>/update/', views.MentalUpdate.as_view(), name='mental-update'),
    path('diary/physical/<int:pk>/update/', views.PhysicalUpdate.as_view(), name='physical-update'),
    path('diary/<int:pk>/update/', views.EmotionalUpdate.as_view(), name='emotional-update'),
    path('diary/physical/<int:pk>/delete/', views.PhysicalDelete.as_view(), name='physical-delete'),
    path('diary/mental/<int:pk>/delete/', views.MentalDelete.as_view(), name='mental-delete'),
    path('diary/<int:pk>/delete/', views.EmotionalDelete.as_view(), name='emotional-delete'),
    path('diary/<int:diary_id>/add_photo', views.add_photo, name="add-photo")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
from django.db import models
from django.urls import reverse 
from django.contrib.auth.models import User

# Create your models here.
MOOD = (
    ('H', 'Happy'),
    ('O', 'Okay'),
    ('D', 'Down'),
    ('S', 'Sad') 
)


class Diary(models.Model):
    date = models.DateField('Entry Date')
    location = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f' {self.user} is at {self.location} on {self.date}'
    
    def get_absolute_url(self):
        return reverse("diary-detail", kwargs={"pk": self.id})
    
    class Meta:
        ordering = ['date']



class Images(models.Model):
    image1 = models.ImageField(default='', upload_to='images/',blank=True, null=True )
    diary_key = models.ForeignKey(Diary, on_delete=models.CASCADE)

class DynamicChoiceField(models.CharField):
    def __init__(self, *args, **kwargs):
        self.user_choices = []
        super().__init__(*args, **kwargs)

    def get_choices(self, include_blank=True, blank_choice=None, **kwargs):
        # Logic to fetch user-specific choices dynamically
        return self.user_choices




class Goals(models.Model):
   goal = DynamicChoiceField(max_length=100, blank=True, null=True)
   def __str__(self):
        return self.goal if self.goal else 'No Goal'


class Physical(models.Model):
    breakfast = models.CharField(max_length=100, blank=True, null=True)
    lunch = models.CharField(max_length=100, blank=True, null=True)
    dinner = models.CharField(max_length=100, blank=True, null=True)
    snacks = models.TextField(max_length=100, blank=True, null=True)
    exercise = models.BooleanField(default=False, blank=True, null=True)
    body_part_worked = models.CharField(blank=True, null=True)
    length_of_workout = models.IntegerField(default=0, blank=True, null=True)
    physical_goals = models.ForeignKey(Goals, on_delete=models.CASCADE, blank=True, null=True)
    workout_link = models.TextField('Type of Workout', blank=True, null=True)
    diary_key = models.ForeignKey(Diary, on_delete=models.CASCADE)
    
    
    
    def __str__(self):
        return f'Breakfast: {self.breakfast}, Lunch: {self.lunch}, Dinner: {self.dinner}, Snacks: {self.snacks}'
    
   
    
class Mental(models.Model):
    meditation = models.BooleanField(default=False, blank=True, null=True)
    time_spent = models.IntegerField(default=0, blank=True, null=True)
    fears = models.TextField(max_length=100, blank=True, null=True)
    desires = models.TextField(max_length=100, blank=True, null=True)
    learning_goals = models.ForeignKey(Goals, on_delete=models.CASCADE, blank=True, null=True)
    diary_key = models.ForeignKey(Diary, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f'Time Spent: {self.time_spent},Fears: {self.fears}, Desires: {self.desires}'
    
    
    
class Emotional(models.Model):
    community_check = models.BooleanField(default=False, blank=True, null=True)
    time_spent = models.IntegerField(default=0, blank=True, null=True)
    community_activities = models.CharField(blank=True, null=True)
    gratitude_list = models.TextField(blank=True, null=True)
    vices = models.TextField("", blank=True, null=True)
    drink = models.BooleanField(default=False, blank=True, null=True)
    number_of_drinks = models.IntegerField(default=0, blank=True, null=True)
    emotional_goals = models.ForeignKey(Goals, on_delete=models.CASCADE, blank=True, null=True)
    evening_mood = models.CharField(
        choices=MOOD,
        default=MOOD[0][0],
        blank=True, 
        null=True
    )
    morning_mood = models.CharField(
        choices=MOOD,
        default=MOOD[0][0],
        blank=True, 
        null=True
    )
    diary_key = models.ForeignKey(Diary, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return f'Activities: {self.community_activities}, Vices: {self.vices}'
    
    
class Photo(models.Model):
    url=models.CharField(max_length=200)
    diary = models.ForeignKey(Diary, on_delete=models.CASCADE)
    def __str__(self):
        return f"Photo for diary_id:' {self.diary_id} @{self.url}"

main_app/forms.py
from django import forms
from .models import Physical, Mental, Emotional, Diary, Goals


class PhysicalForm(forms.ModelForm):
    class Meta:
        model = Physical
        fields = ['breakfast', 'lunch', 'dinner', 'snacks', 'exercise', 'body_part_worked', 'length_of_workout', 'workout_link']
        
class MentalForm(forms.ModelForm):
    class Meta:
        model = Mental
        fields = ['meditation', 'time_spent', 'fears', 'desires']
       
       
        
        
class EmotionalForm(forms.ModelForm):
    class Meta:
        model = Emotional
        fields = ['community_check','time_spent','community_activities' ,'gratitude_list', 'vices','drink', 'number_of_drinks', 'evening_mood' , 'morning_mood']
       
       
class GoalsForm(forms.ModelForm):
    class Meta:
        model = Goals
        fields = '__all__'
        

main_app/views.py
import os
from django.shortcuts import render, redirect
import uuid
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
import requests
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Diary, Physical, Mental, Emotional, Photo, Goals
from django.utils import timezone
from .forms import PhysicalForm, MentalForm, EmotionalForm
import boto3

# Create your views here.



def signup(request):
    error_message=""
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)


@login_required
def diary_index(request):
    today = timezone.now().date()
    diary = Diary.objects.filter(date=today, user=request.user)
    if not diary: 
        diary = Diary.objects.create(user=request.user, date=today)   
    diarys = Diary.objects.filter(user=request.user)
    return render(request, 'diary/index.html', {'diarys': diarys})

@login_required
def diary_detail(request, diary_id):
    today = timezone.now().date()
    diary = Diary.objects.get(id=diary_id)
    physical_form = PhysicalForm()
    mental_form = MentalForm()
    emotional_form = EmotionalForm()
    print(diary_id)
    return render(request, 'diary/detail.html', {'diary': diary, 'today': today == diary.date, 'physical_form': physical_form, 'mental_form': mental_form, 'emotional_form': emotional_form})

@login_required
def add_physical(request, diary_id):
    form = PhysicalForm(request.POST)
    if form.is_valid():
        new_physical = form.save(commit=False)
        new_physical.diary_key_id = diary_id
        new_physical.save()
    return redirect('diary-detail', diary_id=diary_id)


    
class PhysicalUpdate(UpdateView):
    model = Physical
    fields = ['breakfast','lunch', 'dinner', 'snacks', 'exercise', 'body_part_worked', 'length_of_workout', 'workout_link']
    success_url = '/diary/'

   

class PhysicalDelete(DeleteView):
    model = Physical
    success_url = '/diary/'

def add_mental(request, diary_id):
    form = MentalForm(request.POST)
    if form.is_valid():
        new_mental = form.save(commit=False)
        new_mental.diary_key_id = diary_id
        new_mental.save()
    return redirect('diary-detail', diary_id=diary_id)



class MentalUpdate(UpdateView):
    model = Mental
    fields = ['meditation', 'time_spent', 'fears', 'desires']
    success_url = '/diary/'




class MentalDelete(DeleteView):
    model = Mental
    success_url = '/diary/'


@login_required
def add_emotional(request, diary_id):
    form = EmotionalForm(request.POST)
    if form.is_valid():
        new_emotional = form.save(commit=False)
        new_emotional.diary_key_id = diary_id        
        new_emotional.save()
    return redirect('diary-detail', diary_id=diary_id)




class EmotionalUpdate(UpdateView):
    model = Emotional
    fields = ['community_check','time_spent','community_activities' ,'gratitude_list', 'vices','drink', 'number_of_drinks', 'evening_mood' , 'morning_mood']
    success_url = '/diary/'



class EmotionalDelete(DeleteView):
    model = Emotional
    success_url = '/diary/'
    
    

    
@login_required
def home(request):
        diary = Diary.objects.filter(user=request.user)
        response = requests.get('https://zenquotes.io/api/random/q')
        quote = response.json()[0]['q']
        author = response.json()[0]['a']
        print(quote)
        return render(request, 'home.html', {'q': quote, 'a': author, 'diary': diary})

        


def add_photo(request, diary_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):] 
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload.fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, diary_id=diary_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', diary_id=diary_id)

    

main_app/templates/diary/detail.html
{%extends 'base.html' %}
{% load static %}
{%block head %}
<link rel="stylesheet" href="{% static 'css/diary/diary-detail.css' %}" />
{% endblock %}

{% block contentone %}
{% if today %}
<h2> {{diary.date}} </h2>
{% else %}
<h1> {{ diary.date }}</h1>
{% endif %}

<section class="diary-container">
    
    <h3> Physical</h3>
    {% if diary.physical_set.count%}
    {% for diary in diary.physical_set.all%}
    <ul>
        <p style:"background-color: white"> Breakfast: {{diary.breakfast}}</p>
        <p>Lunch: {{diary.lunch}}</p>
        <p>Dinner: {{diary.dinner}}</p>
        <p> Snacks: {{diary.snacks}}</p>
        <p> Area of Focus: {{diary.body_part_worked}}</p>
        <p> Time Spent: {{diary.time_spent}}</p>
        <p> Exercise: {{diary.exercise}}</p>
    </ul>
    <div class='actions'>
        <button><a href="{% url 'physical-update' diary.id%}" class="btn">Edit</a></button>
        <break>
        <button><a href="{% url 'physical-delete' diary.id%}" class="btn">Delete</a></button>
    {% endfor %}
    {% else %}
    <div class="subsection-content">
     
    </div>
    <div class="test">
    <form 
        method="post" 
        class="diary-table" 
        autocomplete="off"
        action="{% url 'add-physical' diary.id%}">
        {%csrf_token%}
        {{ physical_form.as_table }}
        <button type="submit" class="btn submit"> Add Physical Entry</button>
    </form>
</div>
    {% endif %}
</section>
{%endblock%}

{% block contenttwo %}
<section class="diary-container">
    <h3> Mental</h3>
    {% if diary.mental_set.count %}
    {% for diary in diary.mental_set.all%}
    <ul>
        <p>Fears: {{diary.fears}}</p>
        <p>Desires: {{diary.desires}}</p>
        <p> Meditation time: {{diary.time_spent}}</p>
        <p> Meditation:{{diary.meditation}}</p>
       
     
        
    </ul>
    <div class='actions'>
        <button> <a href="{% url 'mental-update' diary.id%}" class="btn">Edit</a></button>
        <button> <a href="{% url 'mental-delete' diary.id%}" class="btn">Delete</a></button>
    {% endfor %}
    {% else %}
    <div class="diary-container">
     
    </div>
    <section class="diary-container">
    <form 
        method="post" 
        class="diary-table" 
        autocomplete="off"
        action="{% url 'add-mental' diary.id%}">
        {%csrf_token%}
        {{ mental_form.as_table }}
       
        <button type="submit" class="btn submit"> Add Mental Entry</button>
    </form>
    </section>
    {% endif %}
</section>
{%endblock%}


{% block contentthree %}
<section class="diary-container emotional">
    <h3> Emotional</h3>
    {% if diary.emotional_set.count %}
    {% for diary in diary.emotional_set.all%}
    <ul>
        <p>Community: {{diary.community_check}}</p>
        <p>Time Spent: {{diary.time_spent}}</p>
        <p>Gratitude List: {{diary.gratitude_list}}</p>
        <p>Morning mood: {{diary.morning_mood}}</p>
        <p>Evening mood: {{diary.evening_mood}}</p>
        
    </ul>
    <div class='actions'>
        <button><a href="{% url 'emotional-update' diary.id%}" class="btn">Edit</a></button>
        <button><a href="{% url 'emotional-delete' diary.id%}" class="btn">Delete</a></button>
    {% endfor %}
    {% else %}
    <div class="subsection-content">
     
    </div>
    <form 
        method="post" 
        class="diary-table" 
        autocomplete="off"
        action="{% url 'add-emotional' diary.id%}">
        {%csrf_token%}
        {{ emotional_form.as_table }}
       
        <button type="submit" class="btn submit"> Add Emotional Entry</button>
    </form>
    {% endif %}


</section>
{%endblock%}

main_app/templates/diary/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href={% static 'css/diary/diary-index.css' %}>
{% endblock %} {% block content %}

<section class="page-header">
    <h1> Your entries </h1>
</section>
<section class="card-container">
    {% for diary in diarys %}
    <div class="card">
        <a href="{% url 'diary-detail' diary.id %}">
            <div class='card-content'>
                <div class="card-img-container">
                    <img
                    src="{% static 'images/diary.jpg' %}"
                    alt="A page"
                    
                    />
                </div>
                <p class="card-title"> {{ diary.date  }} </p>
            </div>
        </a>
    </div>
    {%endfor%}
</section>
{%endblock%}

{%block goal%}
<form 
method="post" 
class="subsection-content" 
autocomplete="off"
action="{% url 'goals-create' goals.id%}">
{%csrf_token%}
{{ goals_form.as_p }}
<button type="submit" class="btn submit"> Add Goal Entry</button>
</form>

{%endblock%}